//======================================================
//---------------| SQL definition start |---------------
//======================================================

//---------------| SQL 2019 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL 2019 Property"),
SMS_Class_ID("EXT|SQL_2019_PROPERTY|1.0")]

Class SQL_2019_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//---------------| SQL 2017 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL 2017 Property"),
SMS_Class_ID("EXT|SQL_2017_PROPERTY|1.0")]

Class SQL_2017_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//---------------| SQL 2016 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL 2016 Property"),
SMS_Class_ID("EXT|SQL_2016_PROPERTY|1.0")]

Class SQL_2016_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//---------------| SQL 2014 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL 2014 Property"),
SMS_Class_ID("EXT|SQL_2014_PROPERTY|1.0")]

Class SQL_2014_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//---------------| SQL 2012 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL 2012 Property"),
SMS_Class_ID("EXT|SQL_2012_PROPERTY|1.0")]

Class SQL_2012_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//---------------| SQL 2008 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL 2008 Property"),
SMS_Class_ID("EXT|SQL_2008_PROPERTY|1.0")]

Class SQL_2008_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//---------------| SQL 2000/2005 definitions |---------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL Legacy Property"),
SMS_Class_ID("EXT|SQL_LEGACY_PROPERTY|1.0")]

Class SQL_Legacy_Property: SMS_Class_Template
{
    [SMS_Report(true), key]    uint32 PropertyIndex;
    [SMS_Report(true), key]    string PropertyName;
    [SMS_Report(true)     ]    uint32 PropertyNumValue;
    [SMS_Report(true)     ]    string PropertyStrValue;
    [SMS_Report(true), key]    string ServiceName;
    [SMS_Report(true), key]    uint32 SqlServiceType;
};

//-------------| SQL ProductID definition |-------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL ProductID"),
SMS_Class_ID("EXT|SQL_PRODUCTID|1.0")]

Class SQL_ProductID: SMS_Class_Template
{
    [SMS_Report(true),  key]    string  Release;
    [SMS_Report(true)      ]    string  ProductID;
    [SMS_Report(true)      ]    boolean DigitalProductID[];
};

//======================================================
//----------------| SQL definition end |----------------
//======================================================
